/*
 * Created on 2019-06-17 ( Time 13:12:46 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package ci.gcorp.aajesepci.dao.entity;

import java.io.Serializable;

import lombok.*;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "member"
 *
 * @author Telosys Tools Generator
 *
 */
@Data
@ToString
@Entity
@Table(name="member" )
public class Member implements Serializable, Cloneable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="firstName", nullable=false, length=255)
    private String     firstname    ;

    @Column(name="lastName", nullable=false, length=255)
    private String     lastname     ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="bornOn", nullable=false)
    private Date       bornon       ;

    @Column(name="gender", nullable=false, length=255)
    private String     gender       ;

    @Column(name="job", nullable=false, length=255)
    private String     job          ;

    @Column(name="email", nullable=false, length=255)
    private String     email        ;

    @Column(name="promoINP", nullable=false, length=255)
    private String     promoinp     ;

    @Column(name="studiedSectorINP", nullable=false, length=255)
    private String     studiedsectorinp ;

    @Column(name="maritalStatus", nullable=false, length=255)
    private String     maritalstatus ;

    @Column(name="nameOfSpouse", nullable=false, length=255)
    private String     nameofspouse ;

    @Column(name="churchAttended", nullable=false, length=255)
    private String     churchattended ;

    @Column(name="placeOfResidence", nullable=false, length=255)
    private String     placeofresidence ;

    @Column(name="isEpici", nullable=false)
    private Byte       isepici      ;

    @Column(name="district", nullable=false, length=255)
    private String     district     ;

    @Column(name="secteur", nullable=false, length=255)
    private String     secteur      ;

    @Column(name="assemblee", nullable=false, length=255)
    private String     assemblee    ;

    @Column(name="responsabilityInChuch", nullable=false, length=255)
    private String     responsabilityinchuch ;

    @Column(name="photo", nullable=false, length=255)
    private String     photo        ;


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Member() {
		super();
    }
    
	//----------------------------------------------------------------------
    // clone METHOD
    //----------------------------------------------------------------------
	@Override
	public java.lang.Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
}
